import Head from 'next/head';
import DocsSection from '../components/DocsSection';
import Header from '../components/Header';
import NewDoc from '../components/NewDoc';
import { useSession } from 'next-auth/react';
import Login from '../components/Login';
import Modal from '../components/Modal';
import { useSelector } from 'react-redux';
import { selectModalIsOpen } from '../features/modalSlice';

function Home() {
  const { data: session } = useSession();
  const modalIsOpen = useSelector(selectModalIsOpen);

  if (!session) return <Login />;

  return (
    <div>
      <Head>
        <title>Google Docs</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <Header />
      {modalIsOpen && <Modal />}

      <section className='bg-[#f8f9fa] pb-10 px-10'>
        <NewDoc />
      </section>
      <section className='px-10 md:px-0'>
        <DocsSection />
      </section>
    </div>
  );
}

export default Home;
